### ISSUE TITLE
Error decoding response when noReply=true

### ISSUE THREAD

**Issue by arrivets** [nknorg/nkn-sdk-flutter#12]
Hi, I am using version `0.3.5` of the package, and calling `sendText` with `noReply=true`.

Something like this: `client.sendText(dests, request.toJson());`.

The message is sent but there is an uncaught exception in the package when it attempts to decode the response:

```
 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'String'                                                                                                      
E/flutter (20876): #0      Client.sendText (package:nkn_sdk_flutter/client.dart:273:7)                                                                                                                                                        
E/flutter (20876): <asynchronous suspension> 
```

The error comes from this function in the package:

https://github.com/nknorg/nkn-sdk-flutter/blob/6da04d81dec4288062da69c5ebff226147323487/lib/client.dart#L260C7-L267C9

The fields of the response are all nil except for `messageID`, and that causes an exception when instantiating the OnMessage object.

**Comment by jiangzhiguo1992** [comment]
@arrivets What platform are you running this code on, android or ios?

**Comment by jiangzhiguo1992** [comment]
@arrivets  At present, the project needs to use the packages(nkn.aar and nkn-sources.jar) compiled from nkn-go-sdk. The packages in the repository does not support the emulator yet. You can try to run it on a real machine.

**Comment by yilunzhang** [comment]
> @arrivets At present, the project needs to use the packages(nkn.aar and nkn-sources.jar) compiled from nkn-go-sdk. The packages in the repository does not support the emulator yet. You can try to run it on a real machine.

This issue seems to be dart only and has nothing to do with the gomobile compiled code
