### ISSUE TITLE
onMessage not called when app in background - iOS release mode

### ISSUE THREAD

**Issue by arrivets** [nknorg/nkn-sdk-flutter#14]
I’m trying to process messages even when the app is in the background.

It works fine on Android and on iOS in debug mode, but not on iOS in release mode. 

On iOS in release mode, the onMessage callback is not called while the app is in the background. But the messages are received because when the app comes back in foreground, the onMessage callback is executed. So it looks like the messages are received and queued, and not consumed until the app comes back in the foreground.

How do you handle this situation in nMobile?
Any ideas on how to process message when app is in background?

**Comment by jiangzhiguo1992** [comment]
onMessage doesn't work when running in background. Since nkn is decentralized, every time the terminal returns to the foreground, the message must be stored immediately to avoid loss. Currently all I can think of is scheduled tasks, but with time intervals.

**Comment by iheron** [comment]
This is due to the characteristics of iOS. When iOS switches to the background, it suspends the code, and debug mode only runs for 30 seconds.
A better approach is to use the iOS background fetch feature, which allows you to consume as many messages as possible within 30 seconds.

**Comment by iheron** [comment]
> Is there a specific reason for this? Looking at the docs for background_fetch, it says that it cannot fire events more frequently than every 15 minutes (https://pub.dev/packages/background_fetch). Does your Task service work differently?

The background fetch is entirely dependent on the intelligent scheduling of the iOS system. It may be called once a week, once a day, or once an hour. But no matter what, it will not be less than 15 minutes.

**Comment by iheron** [comment]
> What are your thoughts on the security considerations of using these propriatary platforms and does this undermine the decentralized nature of the app?

Notification service is optional. User can close it.

**Comment by yilunzhang** [comment]
> What are your thoughts on the security considerations of using these propriatary platforms and does this undermine the decentralized nature of the app?

We try to minimize the potential security issue by using the notification service in a different way (compared to most other apps):
- Push notification token is not stored on server as there is none. Instead it's stored on each device. Each User can choose whoever he trusts to have his token.
- No message content or metadata is sent in notification, only a generic "You have a new message" is sent so minimal information is sent through the push notification service.

**Comment by arrivets** [comment]
Thank you, that makes sense. 
I guess it's noteworthy that when the user accepts this feature, Apple and Google can potentially know who's messaging who. As long as it's optional and documented that's fine in my opinion too.
