### ISSUE TITLE
QQ : Get a new NKN address and public key every time i open the seed in different device 'Hardware'!!!

### ISSUE THREAD

**Issue by HickYeah** [nknorg/nkn-sdk-flutter#9]
Hi There, 

During my testing and development using the NKN network and this SDK, I noticed a behavior and I would like to have a better understanding of how it works. 

Using the same Seed, When I open a connection with the NKN network on multiple Android Emulators I get the SAME NKN address and SAME  public Key, But When I open the connection from a real device, Each real device will have a different NKN address and public key, again the same seed across. 

Is there any explanation for this behavior on the network? Is that normal? If so, How can I keep the NKN address persists across all phones using one seed? 

Thanks,

**Comment by yilunzhang** [comment]
This is not normal. When you pass the same seed, you should always get the same public key, regardless of device or any other factors. If you get a different public key every time, you are probably passing an empty seed so it generates a random one. You might want to double check the seed you passed to sdk

**Comment by HickYeah** [comment]
You're absolutely right, This issue happened to me when I was trying to implement Mnmonic to seed, So during my development, I was cleaning the phrases like spaces and that was the issue, Generate a different list of bytes.

Thank you for responding, You can feel free to close this issue.
